Proposed fix for System.NullReferenceException crash
I ran into the following issue in Painter.iOS and wanted to share what I believe the solution might be:

```
System.NullReferenceException: Object reference not set to an instance of an object
Object reference not set to an instance of an object
PainterView.drawPath ()
PainterView.HandleOrientationChange (Foundation.NSNotification obj)
InternalNSNotificationHandler.Post (Foundation.NSNotification s) /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/src/Foundation/NSNotificationCenter.cs:48
(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/src/UIKit/UIApplication.cs:79
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/src/UIKit/UIApplication.cs:63
```

I believe removing the observer this way may correct the issue:
https://forums.xamarin.com/discussion/comment/95282/#Comment_95282

However, I made this change which is simpler which I believe should fix the issue as well.